image: node:latest

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret

before_script:
  - echo before_script start

stages:
  - install
  - production

install:
  type: build
  stage: install
  image: node:latest
  script:
    - echo Hello CI
    #- npm install
    #- npm run install-all
  only:
    - master

# Deploy to Heroku
production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ninedotproblem --api-key=$HEROKU_API_KEY
  only:
    - master
